server:
  port: 8181
  
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
      - id: USER-SERVICE
        uri: lb://USER-SERVICE
        predicates:
          - Path=/user/**
      - id: BOOK-SERVICE
        uri: lb://BOOK-SERVICE
        predicates:
          - Path=/book/**
      - id: CART-SERVICE
        uri: lb://CART-SERVICE
        predicates:
          - Path=/cart/**
      - id: ORDER-SERVICE
        uri: lb://ORDER-SERVICE
        predicates:
          - Path=/order/** 
             
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/                     